Disable display of author emails
racket/racket-pkg-website pull request #86
Opened 2023-02-13 01:59 UTC by williewillus

The Racket package catalog shows author emails plainly without any redaction or mangling, making it easy for scrapers and scammers to harvest emails. My listed address has been getting tens of spam emails due to this exposure. The only other thing I've used that address for is to comment on the AUR, but the AUR user system does not expose the email address of members, so it's probably the Racket package server.

As comparison, here's what other package hosting sites do:
* OCaml opam does not expose emails
* Python pypi does expose emails
* RubyGems has an account system, but emails are not exposed on profiles
* Rust crates.io has an account system tied to GitHub profiles, emails are not exposed directly crates.io on profiles
* Java Maven central does not expose emails in the UI, but pom.xml files contain them

Altogether, I think we should hide these for now. Users can go to the codeforge/website of the package for contact information.

See issue #77 for more context and discussion.

2023-02-13 02:01 UTC, williewillus commented
Author search is left enabled because the threat of spamming isn't changed by disabling it; if you're a spammer and you already have an email address in hand, there is no point in doing an author search for more packages, you can already start sending spam to the address.

2023-02-18 16:43 UTC, jryans requested changes
Thanks for working on this! 🙂 I'll check in with others who work on the package infrastructure to see what they think about this.

While I'm doing that, it would be good to also hide the author emails shown on the [home page](https://pkgs.racket-lang.org/) table as well.

2023-03-03 03:36 UTC, williewillus commented
Also removed emails from the search results listing

2023-03-04 18:20 UTC, jryans approved these changes
Thanks, this looks good to me! 🙂 

I've discussed this with others involved in package server operations, and we've agreed to proceed with this approach.

2023-03-04 18:20 UTC, merged

2023-03-04 18:21 UTC, jryans commented
I'll work on deploying this change now.

2023-03-04 18:43 UTC, jryans commented
This has now been deployed. 😄 

The server is working on re-rendering each package page, but you can see from the ones that have updated (e.g. https://pkgs.racket-lang.org/package/binutils) that it looks correct.